vacanes_auth_login:
    path:     /login
    defaults: { _controller: "AppBundle:Auth:login" }

vacanes_auth_register:
    path:     /register
    defaults: { _controller: "AppBundle:Auth:register" }
