userOwner:
    path:     /userOwner/{id}
    defaults: { _controller: "AppBundle:Owner:userOwner" }
    options:
        expose: true
    methods:  [GET]

userOwner_create:
    path:     /userOwner
    defaults: { _controller: "AppBundle:Owner:userOwnerCreate" }
    options:
        expose: true
    methods:  [POST]

userOwner_update:
    path:     /userOwner
    defaults: { _controller: "AppBundle:Owner:userOwnerUpdate" }
    options:
        expose: true
    methods:  [PUT]

userOwner_delete:
    path:     /userOwner
    defaults: { _controller: "AppBundle:Owner:userOwnerDelete" }
    options:
        expose: true
    methods:  [DELETE]

dog:
    path:     /dog/{id}
    defaults: { _controller: "AppBundle:Dog:dog" }
    options:
        expose: true
    methods:  [GET]

dog_create:
    path:     /dog
    defaults: { _controller: "AppBundle:Dog:dogCreate" }
    options:
        expose: true
    methods:  [POST]

dog_update:
    path:     /dog
    defaults: { _controller: "AppBundle:Dog:dogUpdate" }
    options:
        expose: true
    methods:  [PUT]

dog_delete:
    path:     /dog
    defaults: { _controller: "AppBundle:Dog:dogDelete" }
    options:
        expose: true
    methods:  [DELETE]
