

dog_photo:
    path:     /dog/{id}/photo
    defaults: { _controller: "AppBundle:Dog:dogPhoto" }
    options:
        expose: true
    methods:  [GET]
    requirements:
        id:  \d+

dog_photo_create:
    path:     /dog/photo
    defaults: { _controller: "AppBundle:Dog:dogPhotoCreate"}
    options:
        expose: true
    methods:  [POST]

dog_photo_delete:
    path:     /dog/photo
    defaults: { _controller: "AppBundle:Dog:dogPhotoDelete" }
    options:
        expose: true
    methods:  [DELETE]

request_requestType:
    path:     /request/request-type
    defaults: { _controller: "AppBundle:Request:requestType" }
    options:
        expose: true
    methods:  [GET]

request_pet_valet:
    path:     /request/pet-valet
    defaults: { _controller: "AppBundle:Request:petValetRequest" }
    options:
        expose: true
    methods:  [POST]

request_day:
    path:     /request/day
    defaults: { _controller: "AppBundle:Request:dayRequest" }
    options:
        expose: true
    methods:  [POST]

request_night:
    path:     /request/night
    defaults: { _controller: "AppBundle:Request:nightRequest" }
    options:
        expose: true
    methods:  [POST]
