#
## User
#

user_update:
    path:     /user
    defaults: { _controller: "AppBundle:User:userUpdate" }
    options:
        expose: true
    methods:  [PUT]

user_delete:
    path:     /user
    defaults: { _controller: "AppBundle:User:userDelete" }
    options:
        expose: true
    methods:  [DELETE]

#
## Owner
#

owner_create:
    path:     /owner
    defaults: { _controller: "AppBundle:Owner:ownerCreate" }
    options:
        expose: true
    methods:  [POST]

owner_update:
    path:     /owner
    defaults: { _controller: "AppBundle:Owner:ownerUpdate" }
    options:
        expose: true
    methods:  [PUT]

owner_delete:
    path:     /owner
    defaults: { _controller: "AppBundle:Owner:ownerDelete" }
    options:
        expose: true
    methods:  [DELETE]

#
## Dog
#

dog:
    path:     /owner/dog
    defaults: { _controller: "AppBundle:Dog:dog" }
    options:
        expose: true
    methods:  [GET]
    requirements:
        id:  \d+

dog_create:
    path:     /owner/dog
    defaults: { _controller: "AppBundle:Dog:dogCreate" }
    options:
        expose: true
    methods:  [POST]

dog_update:
    path:     /owner/dog/edit
    defaults: { _controller: "AppBundle:Dog:dogUpdate" }
    options:
        expose: true
    methods:  [POST]

dog_delete:
    path:     /owner/dog
    defaults: { _controller: "AppBundle:Dog:dogDelete" }
    options:
        expose: true
    methods:  [DELETE]

dog_sizes:
    path:     /owner/dog-sizes
    defaults: { _controller: "AppBundle:Dog:dogSizes" }
    options:
        expose: true
    methods:  [GET]

dog_breeds:
    path:     /owner/dog-breeds
    defaults: { _controller: "AppBundle:Dog:dogBreeds" }
    options:
        expose: true
    methods:  [GET]

#
## Requests
#

request_requestType:
    path:     /request/request-type
    defaults: { _controller: "AppBundle:Request:requestType" }
    options:
        expose: true
    methods:  [GET]

request_pet_valet:
    path:     /request
    defaults: { _controller: "AppBundle:Request:request" }
    options:
        expose: true
    methods:  [POST]

request_day:
    path:     /request/day
    defaults: { _controller: "AppBundle:Request:dayRequest" }
    options:
        expose: true
    methods:  [POST]

request_night:
    path:     /request/night
    defaults: { _controller: "AppBundle:Request:nightRequest" }
    options:
        expose: true
    methods:  [POST]

owner_responses:
    path:   /owner/responses
    defaults: { _controller: "AppBundle:Owner:ownerResponses" }
    options:
        expose: true
    methods:  [POST]

owner_response:
    path:   /owner/response/{id}
    defaults: { _controller: "AppBundle:Owner:ownerResponse" }
    options:
        expose: true
    methods:  [GET]

owner_hire_response:
    path:   /owner/hire-response/{id}
    defaults: { _controller: "AppBundle:Owner:ownerHireResponse" }
    options:
        expose: true
    methods:  [GET]

owner_hired_response:
    path:   /owner/hired-response
    defaults: { _controller: "AppBundle:Owner:ownerHiredResponse" }
    options:
        expose: true
    methods:  [POST]

#
## Watcher
#

watcher_create:
    path:     /watcher
    defaults: { _controller: "AppBundle:Watcher:watcherCreate" }
    options:
        expose: true
    methods:  [POST]

watcher_update:
    path:     /watcher/edit
    defaults: { _controller: "AppBundle:Watcher:watcherUpdate" }
    options:
        expose: true
    methods:  [POST]

watcher_delete:
    path:     /watcher
    defaults: { _controller: "AppBundle:Watcher:watcherDelete" }
    options:
        expose: true
    methods:  [DELETE]

watcher_requests:
    path:     /watcher/requests
    defaults: { _controller: "AppBundle:Watcher:watcherRequests" }
    options:
        expose: true
    methods:  [POST]

watcher_request:
    path:     /watcher/request/{id}
    defaults: { _controller: "AppBundle:Watcher:watcherRequest" }
    options:
        expose: true
    methods:  [GET]

watcher_response:
    path:     /watcher/response
    defaults: { _controller: "AppBundle:Watcher:watcherResponse" }
    options:
        expose: true
    methods:  [POST]
