user_update:
    path:     /user
    defaults: { _controller: "AppBundle:User:userUpdate" }
    options:
        expose: true
    methods:  [PUT]

user_delete:
    path:     /user
    defaults: { _controller: "AppBundle:User:userDelete" }
    options:
        expose: true
    methods:  [DELETE]

owner_create:
    path:     /owner
    defaults: { _controller: "AppBundle:Owner:ownerCreate" }
    options:
        expose: true
    methods:  [POST]

owner_update:
    path:     /owner
    defaults: { _controller: "AppBundle:Owner:ownerUpdate" }
    options:
        expose: true
    methods:  [PUT]

owner_delete:
    path:     /owner
    defaults: { _controller: "AppBundle:Owner:ownerDelete" }
    options:
        expose: true
    methods:  [DELETE]
