NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

auth:
    resource: "@AppBundle/Resources/config/routing/auth.yml"
    prefix:   /auth

user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user
