services:
    vacanes.auth:
        class: AppBundle\EventListener\TokenListener
        arguments:
            - "%tokens%"
            - @users.manager
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    users.manager:
        class: AppBundle\Model\UserManager
        arguments:
            - @doctrine.orm.entity_manager
            - AppBundle\Entity\User

    users.type:
        class: AppBundle\Form\UserType
        tags:
            - { name: form.type, alias: v_user }

    response_bag.utils:
        class: AppBundle\Utils\ResponseBag
