services:
    vacanes.auth:
        class: AppBundle\EventListener\TokenListener
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    users.type:
        class: AppBundle\Form\UserType
        tags:
            - { name: form.type, alias: v_user }

    response_bag.utils:
        class: AppBundle\Utils\ResponseBag

    request.service:
        class: AppBundle\EventListener\RequestServiceListener
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_listener, event: request.service, method: onRequestService }
        calls:
            - [setContainer, ['@service_container']]

    response.service:
        class: AppBundle\EventListener\ResponseServiceListener
        tags:
            - { name: kernel.event_listener, event: response.service, method: onResponseService }
        calls:
            - [setContainer, ['@service_container']]

    response_hide.service:
        class: AppBundle\EventListener\ResponseHireListener
        tags:
            - { name: kernel.event_listener, event: response.service, method: onResponseHire }
