AppBundle\Entity\User:
    properties:
        facebookId:
            - NotBlank: ~
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~

AppBundle\Entity\UserOwner:
    properties:
        address:
            - NotBlank: ~
        latitude:
            - NotBlank: ~
        longitude:
            - NotBlank: ~
        user:
            - NotBlank: ~
