AppBundle\Entity\User:
    properties:
        facebookId:
            - NotBlank: ~
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~

AppBundle\Entity\Owner:
    properties:
        address:
            - NotBlank: ~
        latitude:
            - NotBlank: ~
            - Type: { type: integer, message: Pailas }
        longitude:
            - NotBlank: ~
            - Type: { type: integer }
        user:
            - NotBlank: ~
            - Type: { type: object }

AppBundle\Entity\Dog:
    properties:
        name:
            - NotBlank: ~
        dogSize:
            - NotBlank: ~
        dogBreed:
            - NotBlank: ~

AppBundle\Entity\Request:
    properties:
        address:
            - NotBlank: ~
        requestType:
            - NotBlank: ~

AppBundle\Entity\PetValetRequest:
    properties:
        serviceDate:
            - NotBlank: ~
            - Date: ~
        startTime:
            - NotBlank: ~
            - Time: ~
        endTime:
            - NotBlank: ~
            - Time: ~

AppBundle\Entity\DayRequest:
    properties:
        startDate:
            - NotBlank: ~
            - Date: ~
        endDate:
            - NotBlank: ~
            - Date: ~
        startTime:
            - NotBlank: ~
            - Time: ~
        endTime:
            - NotBlank: ~
            - Time: ~
        serviceType:
            - NotBlank: ~
        serviceDays:
            - NotBlank: ~
            - Type: { type: integer }

AppBundle\Entity\NightRequest:
    properties:
        startDate:
            - NotBlank: ~
        endDate:
            - NotBlank: ~
        startTime:
            - NotBlank: ~
        endTime:
            - NotBlank: ~
        serviceType:
            - NotBlank: ~

AppBundle\Entity\Watcher:
    properties:
        bios:
            - NotBlank: ~
        telephone:
            - NotBlank: ~
            - Type: { type: integer }

# AppBundle\Entity\PlacePhoto:
#     properties:
#         file:
#             - Image: ~
