AppBundle\Entity\User:
    properties:
        facebookId:
            - NotBlank: ~
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~

AppBundle\Entity\Owner:
    properties:
        address:
            - NotBlank: ~
        latitude:
            - NotBlank: ~
        longitude:
            - NotBlank: ~
        user:
            - NotBlank: ~

AppBundle\Entity\Dog:
    properties:
        name:
            - NotBlank: ~
        dogSize:
            - NotBlank: ~
        dogBreed:
            - NotBlank: ~

AppBundle\Entity\Request:
    properties:
        address:
            - NotBlank: ~
        requestType:
            - NotBlank: ~

AppBundle\Entity\PetValetRequest:
    properties:
        # request:
        #     - NotBlank: ~
        serviceDate:
            - NotBlank: ~
        startTime:
            - NotBlank: ~
        endTime:
            - NotBlank: ~

AppBundle\Entity\DayRequest:
    properties:
        request:
            - NotBlank: ~
        startDate:
            - NotBlank: ~
        endDate:
            - NotBlank: ~
        serviceDate:
            - NotBlank: ~
        startTime:
            - NotBlank: ~
        endTime:
            - NotBlank: ~
        serviceType:
            - NotBlank: ~
        serviceDays:
            - NotBlank: ~

AppBundle\Entity\NightRequest:
    properties:
        request:
            - NotBlank: ~
        startDate:
            - NotBlank: ~
        endDate:
            - NotBlank: ~
        serviceDate:
            - NotBlank: ~
        startTime:
            - NotBlank: ~
        endTime:
            - NotBlank: ~
        serviceType:
            - NotBlank: ~
