AppBundle\Entity\User:
    properties:
        facebookId:
            - NotBlank: ~
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        email:
            - NotBlank: ~
