AppBundle\Entity\User:
    properties:
        facebookId:
            - NotBlank: ~
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~

AppBundle\Entity\Owner:
    properties:
        address:
            - NotBlank: ~
        latitude:
            - NotBlank: ~
        longitude:
            - NotBlank: ~
        user:
            - NotBlank: ~

AppBundle\Entity\Dog:
    properties:
        name:
            - NotBlank: ~
        dogSize:
            - NotBlank: ~
        dogBreed:
            - NotBlank: ~
