AppBundle\Entity\User:
    user{1..100}:
        facebookId: <lat()>
        firstName: <firstName()>
        lastName: <lastName()>
        email: <email()>
        token: <randomFloat()>
        latitude: <lat()>
        longitude: <lng()>

AppBundle\Entity\Watcher:
    watcher_{1..100}:
        bios: <paragraph()>
        telephone: <randomFloat()>
        user: @user<current()>

AppBundle\Entity\DogSize:
    small:
        name: Small
    medium:
        name: Medium
    large:
        name: Large

AppBundle\Entity\DogBreed:
    breed1:
        name: Breed1
    breed2:
        name: Breed2
    breed3:
        name: Breed3
    breed4:
        name: Breed4

AppBundle\Entity\RequestType:
    rt1:
        name: Day Request
        description: --
        type: day_request
    rt2:
        name: Night Request
        description: --
        type: night_request
    rt3:
        name: Pet Valet
        description: --
        type: pet_valet
