<?php

namespace AppBundle\Entity;

/**
 * CalificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalificationsRepository extends \Doctrine\ORM\EntityRepository
{
}
