<?php

namespace AppBundle\Entity;

/**
 * CalificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalificationRepository extends \Doctrine\ORM\EntityRepository
{
}
