<?php

namespace AppBundle\Entity;

/**
 * DayRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayRequestsRepository extends \Doctrine\ORM\EntityRepository
{
}
