<?php

namespace AppBundle\Entity;

/**
 * DayRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
