<?php

namespace AppBundle\Entity;

/**
 * DayServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
