<?php

namespace AppBundle\Entity;

/**
 * DogBreedsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogBreedsRepository extends \Doctrine\ORM\EntityRepository
{
}
