<?php

namespace AppBundle\Entity;

/**
 * DogOwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogOwnerRepository extends \Doctrine\ORM\EntityRepository
{
}
