<?php

namespace AppBundle\Entity;

/**
 * DogPhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogPhotosRepository extends \Doctrine\ORM\EntityRepository
{
}
