<?php

namespace AppBundle\Entity;

/**
 * DogPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
