<?php

namespace AppBundle\Entity;

/**
 * DogSizesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogSizesRepository extends \Doctrine\ORM\EntityRepository
{
}
