<?php

namespace AppBundle\Entity;

/**
 * DogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogsRepository extends \Doctrine\ORM\EntityRepository
{
}
