<?php

namespace AppBundle\Entity;

/**
 * DogsBreedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogsBreedsRepository extends \Doctrine\ORM\EntityRepository
{
}
