<?php

namespace AppBundle\Entity;

/**
 * DogsPhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogsPhotosRepository extends \Doctrine\ORM\EntityRepository
{
}
