<?php

namespace AppBundle\Entity;

/**
 * FavoriteWatchersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteWatchersRepository extends \Doctrine\ORM\EntityRepository
{
}
