<?php

namespace AppBundle\Entity;

/**
 * IOSDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IOSDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
