<?php

namespace AppBundle\Entity;

/**
 * NightRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NightRequestsRepository extends \Doctrine\ORM\EntityRepository
{
}
