<?php

namespace AppBundle\Entity;

/**
 * NightRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NightRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
