<?php

namespace AppBundle\Entity;

/**
 * PetValetRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetValetRequestsRepository extends \Doctrine\ORM\EntityRepository
{
}
