<?php

namespace AppBundle\Entity;

/**
 * PetValetRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetValetRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
