<?php

namespace AppBundle\Entity;

/**
 * PlacesPhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacesPhotosRepository extends \Doctrine\ORM\EntityRepository
{
}
