<?php

namespace AppBundle\Entity;

/**
 * PlacePhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacePhotosRepository extends \Doctrine\ORM\EntityRepository
{
}
