<?php

namespace AppBundle\Entity;

/**
 * RequestsDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestsDayRepository extends \Doctrine\ORM\EntityRepository
{
}
