<?php

namespace AppBundle\Entity;

/**
 * RequestNightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestNightRepository extends \Doctrine\ORM\EntityRepository
{
}
