<?php

namespace AppBundle\Entity;

/**
 * RequestsPetValetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestsPetValetRepository extends \Doctrine\ORM\EntityRepository
{
}
