<?php

namespace AppBundle\Entity;

/**
 * RequestTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
