<?php

namespace AppBundle\Entity;

/**
 * ResponsesCalificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsesCalificationRepository extends \Doctrine\ORM\EntityRepository
{
}
