<?php

namespace AppBundle\Entity;

/**
 * ServicesTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
