<?php

namespace AppBundle\Entity;

/**
 * ServiceTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
