<?php

namespace AppBundle\Entity;

/**
 * ServiceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
