<?php

namespace AppBundle\Entity;

/**
 * SizesTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizesTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
