<?php

namespace AppBundle\Entity;

/**
 * TypesRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypesRequestsRepository extends \Doctrine\ORM\EntityRepository
{
}
