<?php

namespace AppBundle\Entity;

/**
 * UsersOwnersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersOwnersRepository extends \Doctrine\ORM\EntityRepository
{
}
