<?php

namespace AppBundle\Entity;

/**
 * UsersWatchersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersWatchersRepository extends \Doctrine\ORM\EntityRepository
{
}
