<?php

namespace AppBundle\Entity;

/**
 * UserWatcherRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWatcherRequestsRepository extends \Doctrine\ORM\EntityRepository
{
}
