<?php

namespace AppBundle\Entity;

/**
 * UserWatchersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWatchersRepository extends \Doctrine\ORM\EntityRepository
{
}
