<?php

namespace AppBundle\Entity;

/**
 * WatcherRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatcherRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
