<?php

namespace AppBundle\Entity;

/**
 * WatcherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatcherRepository extends \Doctrine\ORM\EntityRepository
{
}
