<?php

namespace AppBundle\Entity;

/**
 * WatcherAllowedSizesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WatcherAllowedSizesRepository extends \Doctrine\ORM\EntityRepository
{
}
